// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recruitment_process_portal_server.Data;

#nullable disable

namespace recruitment_process_portal_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("recruitment_process_portal_server.Models.AcquisitionSource", b =>
                {
                    b.Property<int>("SourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceID"));

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SourceID");

                    b.ToTable("AcquisitionSources");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.AppUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.ApplicationStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.ToTable("ApplicationStatuses");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int?>("VerifiedByUserID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("CandidateID");

                    b.HasIndex("StatusID");

                    b.HasIndex("VerifiedByUserID");

                    b.ToTable("CandidateDocuments");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateProfile", b =>
                {
                    b.Property<int>("CandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateID"));

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeRawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CandidateID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("SourceID");

                    b.HasIndex("UserID");

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("VerifiedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("CandidateID", "SkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("VerifiedByUserID");

                    b.ToTable("CandidateSkill");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.ClosureReason", b =>
                {
                    b.Property<int>("ReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonID"));

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReasonID");

                    b.ToTable("ClosureReasons");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.DocVerifyStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.ToTable("DocVerifyStatuses");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.EmployeeRecord", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobPositionPositionID")
                        .HasColumnType("int");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CandidateID");

                    b.HasIndex("JobPositionPositionID");

                    b.ToTable("EmployeeRecords");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewPanel", b =>
                {
                    b.Property<int>("InterviewID")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerUserID")
                        .HasColumnType("int");

                    b.Property<string>("PanelRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InterviewID", "InterviewerUserID");

                    b.HasIndex("InterviewerUserID");

                    b.ToTable("InterviewPanels");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewResult", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewID")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerUserID")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("ResultID");

                    b.HasIndex("InterviewID");

                    b.HasIndex("InterviewerUserID");

                    b.ToTable("InterviewResults");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewSchedule", b =>
                {
                    b.Property<int>("InterviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewID"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JobCandidateLinkLinkID")
                        .HasColumnType("int");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("InterviewID");

                    b.HasIndex("JobCandidateLinkLinkID");

                    b.HasIndex("LinkID");

                    b.HasIndex("TypeID");

                    b.ToTable("InterviewSchedules");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeID");

                    b.ToTable("InterviewTypes");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobCandidateLink", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<int?>("CandidateProfileCandidateID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("JobPositionPositionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LinkedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.HasKey("LinkID");

                    b.HasIndex("CandidateID");

                    b.HasIndex("CandidateProfileCandidateID");

                    b.HasIndex("CurrentStatusID");

                    b.HasIndex("JobPositionPositionID");

                    b.HasIndex("LinkedByUserID");

                    b.HasIndex("PositionID");

                    b.ToTable("JobCandidateLinks");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobPosition", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<int?>("ClosureReasonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventID")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedCandidateID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PositionID");

                    b.HasIndex("ClosureReasonID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("EventID");

                    b.HasIndex("SelectedCandidateID");

                    b.HasIndex("StatusID");

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobSkillDefinition", b =>
                {
                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMinimum")
                        .HasColumnType("bit");

                    b.HasKey("PositionID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("JobSkillDefinitions");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.OfferLetter", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferID"));

                    b.Property<decimal>("CTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OfferID");

                    b.HasIndex("LinkID");

                    b.ToTable("OfferLetters");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.RecruitmentEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("RecruitmentEvents");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.ScreeningFeedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerUserID")
                        .HasColumnType("int");

                    b.Property<string>("ScreeningDecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("LinkID");

                    b.HasIndex("ReviewerUserID");

                    b.ToTable("ScreeningFeedbacks");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.SkillRating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ResultID")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.HasIndex("ResultID");

                    b.HasIndex("SkillID");

                    b.ToTable("SkillRatings");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.StatusChangeLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<int>("NewStatusID")
                        .HasColumnType("int");

                    b.Property<int>("OldStatusID")
                        .HasColumnType("int");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("LogID");

                    b.HasIndex("ChangedByUserID");

                    b.HasIndex("LinkID");

                    b.HasIndex("NewStatusID");

                    b.HasIndex("OldStatusID");

                    b.ToTable("StatusChangeLogs");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.UserRole", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "Manages job openings, candidates, interviews",
                            RoleName = "Recruiter"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "Culture fit, negotiations, documentation",
                            RoleName = "HR"
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "Provides interview feedback",
                            RoleName = "Interviewer"
                        },
                        new
                        {
                            RoleID = 4,
                            Description = "Screens CVs and shortlists candidates",
                            RoleName = "Reviewer"
                        },
                        new
                        {
                            RoleID = 5,
                            Description = "Manages users, roles, system configuration",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 6,
                            Description = "Applies to jobs and uploads documents",
                            RoleName = "Candidate"
                        },
                        new
                        {
                            RoleID = 7,
                            Description = "Read-only access to system data",
                            RoleName = "Viewer"
                        });
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.AppUser", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateDocument", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.DocVerifyStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserID");

                    b.Navigation("Candidate");

                    b.Navigation("Status");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateProfile", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID");

                    b.HasOne("recruitment_process_portal_server.Models.AcquisitionSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateSkill", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Candidate");

                    b.Navigation("Skill");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.EmployeeRecord", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionPositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewPanel", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.InterviewSchedule", "InterviewSchedule")
                        .WithMany("InterviewPanels")
                        .HasForeignKey("InterviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "InterviewerUser")
                        .WithMany()
                        .HasForeignKey("InterviewerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewSchedule");

                    b.Navigation("InterviewerUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewResult", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.InterviewSchedule", "InterviewSchedule")
                        .WithMany("InterviewResults")
                        .HasForeignKey("InterviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewSchedule");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewSchedule", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.JobCandidateLink", null)
                        .WithMany("InterviewSchedules")
                        .HasForeignKey("JobCandidateLinkLinkID");

                    b.HasOne("recruitment_process_portal_server.Models.JobCandidateLink", "JobCandidateLink")
                        .WithMany()
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.InterviewType", "InterviewType")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewType");

                    b.Navigation("JobCandidateLink");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobCandidateLink", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", null)
                        .WithMany("JobCandidateLinks")
                        .HasForeignKey("CandidateProfileCandidateID");

                    b.HasOne("recruitment_process_portal_server.Models.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.JobPosition", null)
                        .WithMany("JobCandidateLinks")
                        .HasForeignKey("JobPositionPositionID");

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "LinkedByUser")
                        .WithMany()
                        .HasForeignKey("LinkedByUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("recruitment_process_portal_server.Models.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("CandidateProfile");

                    b.Navigation("JobPosition");

                    b.Navigation("LinkedByUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobPosition", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.ClosureReason", "ClosureReason")
                        .WithMany()
                        .HasForeignKey("ClosureReasonID");

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.RecruitmentEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");

                    b.HasOne("recruitment_process_portal_server.Models.CandidateProfile", "SelectedCandidate")
                        .WithMany()
                        .HasForeignKey("SelectedCandidateID");

                    b.HasOne("recruitment_process_portal_server.Models.JobStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosureReason");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Event");

                    b.Navigation("SelectedCandidate");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobSkillDefinition", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.JobPosition", "JobPosition")
                        .WithMany("JobSkillDefinitions")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.OfferLetter", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.JobCandidateLink", "JobCandidateLink")
                        .WithMany("OfferLetters")
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobCandidateLink");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.RecruitmentEvent", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.ScreeningFeedback", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.JobCandidateLink", "JobCandidateLink")
                        .WithMany("ScreeningFeedbacks")
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobCandidateLink");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.SkillRating", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.InterviewResult", "InterviewResult")
                        .WithMany("SkillRatings")
                        .HasForeignKey("ResultID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewResult");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.StatusChangeLog", b =>
                {
                    b.HasOne("recruitment_process_portal_server.Models.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.JobCandidateLink", "JobCandidateLink")
                        .WithMany("StatusChangeLogs")
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.ApplicationStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("recruitment_process_portal_server.Models.ApplicationStatus", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("JobCandidateLink");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.CandidateProfile", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobCandidateLinks");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewResult", b =>
                {
                    b.Navigation("SkillRatings");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.InterviewSchedule", b =>
                {
                    b.Navigation("InterviewPanels");

                    b.Navigation("InterviewResults");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobCandidateLink", b =>
                {
                    b.Navigation("InterviewSchedules");

                    b.Navigation("OfferLetters");

                    b.Navigation("ScreeningFeedbacks");

                    b.Navigation("StatusChangeLogs");
                });

            modelBuilder.Entity("recruitment_process_portal_server.Models.JobPosition", b =>
                {
                    b.Navigation("JobCandidateLinks");

                    b.Navigation("JobSkillDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
